[tool.poetry]
name = "pdfcutlass"
version = "0.1.0"
description = ""
authors = ["Dylan Yang <dylany360@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pypdf = "^3.17.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
